### ISSUE TITLE
CF CFLI outdated

### ISSUE THREAD

**Issue by mastertinner** [alphagov/paas-docker-cloudfoundry-tools#81]
Can we please rebuild the `governmentpaas/cf-cli` image? The CLI is outdated (6.21.1 whereas the latest one is 6.23.1).

**Comment by combor** [comment]
Hi, thanks for reporting this. I've created PR https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/87 to update `cf cli` binary.

**Comment by dcarley** [comment]
@mastertinner It's been published now: https://hub.docker.com/r/governmentpaas/cf-cli/builds/bhj5lzmkqqtkxxfp2rxm5tc/

I'm glad the images are of use to you! I'd like to note though that we consider the project as ["coding in the open" rather than "open source"](https://gds.blog.gov.uk/2012/10/12/coding-in-the-open/), so we can't guarantee that we won't make a backwards incompatible change in the future, especially as we don't currently use semantic versioning for containers.
